### ISSUE TITLE
REST API for the project

### ISSUE THREAD

**Issue by talbenbasat** [Bahmni/openmrs-module-bahmniapps#28]
Hi,

I wish to use this project.

I was wondering:
1. how can I deploy it locally on my development system.
its a linux station?

2. does the system have a REST API for action like:
- Add client?
- get client name?
- more

Thanks,
Tal

**Comment by gsluthra** [comment]
Hi @talbenbasat. We use OpenMRS talk for discussions / questions. You can post your questions here: https://talk.openmrs.org/c/software/bahmni.

Do setup Bahmni, you can follow these steps: https://bahmni.atlassian.net/wiki/display/BAH/Install+Bahmni+on+CentOS

For Dev, you can follow: https://bahmni.atlassian.net/wiki/display/BAH/Setting+up+Bahmni+Dev+Environment

Yes - Bahmni does have a REST API. The Angular JS app uses REST to communicate to the backend API. 

I am marking this as closed. If you have further questions, please post them on OpenMRS Talk. Thanks!

**Comment by talbenbasat** [comment]
The openMRS shows error, I've opened a ticket.

Can you just please let me know if I can:
1. get patient list, and query it by names or id?
2. check availability slots? 
3. post a appointment to the system? 

or just give me a link to the REST API documentation

Thanks
