### ISSUE TITLE
Travis builds not running

### ISSUE THREAD

**Issue by mdjnewman** [Bahmni/openmrs-module-bahmniapps#35]
A .travis.yml file was added in #29 (I've made some fixes in #34 that's open now), but builds on Travis aren't running ([build history](https://travis-ci.org/Bahmni/openmrs-module-bahmniapps/builds) shows the last build was on 2016-01-29).

@sravanthi17 has been helping with this and has checked the settings in Travis, which seem fine.

Looking at the [Travis requests page](https://travis-ci.org/Bahmni/openmrs-module-bahmniapps/requests), it seems that Travis isn't getting push notifications from Github.

The only thing I can think of is that the integration has been deleted on the Github side. Can someone check https://github.com/Bahmni/openmrs-module-bahmniapps/settings/installations and see if Travis CI is listed there?

If it's not, it can be brought back to life be toggling the repo off and on again at https://travis-ci.org/profile/Bahmni.

**Comment by sravanthi17** [comment]
Hi @mdjnewman : Travis Ci is not listed. Will try toggling the repo. Thanks for your help

**Comment by mdjnewman** [comment]
Hi! Awesome, hopefully this is what was preventing it from working :)

**Comment by mdjnewman** [comment]
Looks like this is sorted - the build for #34 was triggered when I pushed a change after you toggled the repo:

https://travis-ci.org/Bahmni/openmrs-module-bahmniapps/builds/169686586

🎉 🎈 👍 

(now we just need to fix up the failing tests...)

**Comment by mdjnewman** [comment]
Closing this now 😄
