### ISSUE TITLE
Issue on login page after linking host machine compiled code with the Vagrant filesystem.

### ISSUE THREAD

**Issue by bolatkazybayev** [Bahmni/openmrs-module-bahmniapps#53]
Hi there,
There are issues after a cloning Bahmni EMR UI Project and linking with the Bahmni. `sudo ln -s /bahmni/openmrs-module-bahmniapps/ui/dist/ /var/www/bahmniapps`
When I request the login page, https://192.168.33.10/bahmni/home/index.html#/login, angular.js:10967 tries to download a files -- https://192.168.33.10/cgi-bin/systemdate and https://192.168.33.10/bahmni_config/openmrs/apps/home/whiteLabel.json. But there is no such files. How to fix that?
Information to repdrocude a bag: 
1. CentOS 6.7
2. The last version of Bahmni -- 088.

**Comment by deepaucksharma** [comment]
@bolatkazybayev  0.88 version of bahmniapps is here - https://github.com/Bahmni/openmrs-module-bahmniapps/tree/release-0.88

**Comment by bolatkazybayev** [comment]
@deepaucksharma thank you for your answer, but it does not help me. Moreover, there is another issue: https://192.168.33.10/bahmni_config/openmrs/apps/home/locale_languages.json in addiotion to whiteLabel.json and systemdate. So, what is wrong?

**Comment by deepaucksharma** [comment]
I think you are trying to run master/current version of bahmniapps, which will be released as 0.89 soon.  So you can either 
1) get the matching version of bahmniapps i.e. bahmniapps on 'release-0.88' branch 
or
2) if you want to work on master branch of bahmniapps, you need to remove bahmni 88 version and install latest dev version. Latest bahmni installer can be found here - http://repo.mybahmni.org.s3.amazonaws.com/rpm/bahmni/bahmni-installer-0.89-128.noarch.rpm

**Comment by bolatkazybayev** [comment]
@deepaucksharma thank you for your help! Now it works. You were right, I tried to run master version. Then I used this command to clone spefic branch:
`git clone -b release-0.88 https://github.com/Bahmni/openmrs-module-bahmniapps.git`
