### ISSUE TITLE
Docker compose file not found

### ISSUE THREAD

**Issue by subhasisbanik** [Bahmni/openmrs-module-bahmniapps#703]
Hello,
I am trying to set up the same in docker and am following :
https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3117449349/Bahmni-Web+Configurations+docker

However, as mentioned in #4, I am trying to update the docker-compose file for starting the service up but as I can see that the file is not present.
Any guidance here?

**Comment by rahu1ramesh** [comment]
Hey @subhasisbanik,

The docker compose files for both bahmni-lite and bahmni-standard are available [here](https://github.com/Bahmni/bahmni-docker). Thanks for your interest in Bahmni.

**Comment by rahu1ramesh** [comment]
> Hey @subhasisbanik,
> 
> The docker compose files for both bahmni-lite and bahmni-standard are available [here](https://github.com/Bahmni/bahmni-docker). Thanks for your interest in Bahmni.
